### PR TITLE
make boundary consumption multipart aware

### PR DESCRIPTION
**Pull request by nicolas-cherel**
That handles the CRLF and double dash suffixes

### CODE REVIEW

**Comment by cybergeek94** [comment]
I'm working on a branch that makes testing more robust. I'd like to merge that first and then have you rebase against it, if you don't mind.

Can you check to make sure that there's no other places where `.consume_boundary()` is called?

**Comment by nicolas-cherel** [comment]
Ok, checked it's the only call site for `.consume_boundary()`

**Comment by nicolas-cherel** [comment]
Ok, merged. Note that this PR conflicts with #9, and I don't know which one you prefer.

**Comment by cybergeek94** [comment]
Done.

There's another concern we need to look at. Right now, `BoundaryReader` will keep yielding bytes until the stream returns EOF, but this is technically incorrect: once `--{boundary}--` is read, we're not allowed to consider anymore bytes in the stream. So `BoundaryReader` *must* be able to consider the two bytes after the last boundary so it can fuse itself if it sees that second `--`.

**Comment by nicolas-cherel** [comment]
Yes, exactly, it crossed my mind, but I didn't know where to put the state tracking. I think it's safe to always read the line after the boundary, and checking it against either `--\r\n` or `\r\n`.

**Comment by cybergeek94** [comment]
According to the spec there's no CRLF after `--boundary--` so we can't assume that. And the other issue asking the reader to continue reading is that it will try to load up to the next boundary in memory, when really all we care about is the next two bytes. I think it's safe to have `BoundaryReader` be aware of this. In fact, it needs to because `Multipart` relies on it returning EOF to say the stream is done.

**Comment by cybergeek94** [comment]
Okay, you were right. :smile: I added the fusing behavior to `Multipart` instead of `BoundaryReader`. But I also have a logic error in `BoundaryReader` I fixed.

**Comment by nicolas-cherel** [comment]
Hum, was right with a bit of luck, I was about to check the spec :)

**Comment by cybergeek94** [comment]
I have pushed a new branch, `logic_fixes`. My Windows machine isn't giving me a good backtrace so I have to load up a Linux VM.

**Comment by cybergeek94** [comment]
I just kinda went ahead and fixed everything, (#14) Hope you don't mind. :grinning:

**Pull request closed without merging**
