### PR TITLE
Bring `multipart` back from the dead!

### LINKED ISSUE #2: Is this dead?
Hi there,

it seems like this repo died a few months ago. Any plans to continue this project? Or are there any good alternatives?

### PR DESCRIPTION
**Pull request by cybergeek94**
Special thanks to @LukasKalbertodt for rewriting the Travis CI script and motivating me to revive this old repo in the first place. (Will update to use GitHub Pages for docs hosting later)

Massive changes, let's see if I can sum them up briefly:

Library-wide changes:
* updated to latest Rust and Hyper APIs
* builds on Rust stable (!!!)
* decoupled the `client` and `server` modules (previously shared data structs)
* moved MIME type guessing to external crate
* `hyper` integration is now optional, can support other HTTP libs in the future as well as user types
    * happy consequence: now possible to mock out the HTTP backend in tests
* de-cluttered `src/lib.rs` (still has some utility functions that don't really have a better place to go)
* full Crates.io integration, no more Git refs
* more complete documentation thanks to `#![warn(missing_docs)]`
* generally improved API ergonomics

Client API:
* got rid of all trait objects and unnecessary allocations, now writes directly to the stream
* redesigned API to support method chaining while making errors less of a pain to deal with (RFC on actual ergonomics of this design)
* `Multipart` doesn't care anymore about whether the request is sized or not, except for one convenience method
* eliminated most panics/asserts

Server API:
* `BoundaryReader` no longer reinvents the wheel WRT buffering, also probably fixed some logic errors that were hard to diagnose
* nested boundaries are still not supported, but will be easier to implement and shouldn't trip up parsing if they do appear
* made multipart data parsing easier to hack on by giving each header its own object responsible for it
* cut out a lot of unnecessary allocations in parsing
* eliminated all but one `unsafe` block (which is copied *ad verbatim* from a stdlib unstable function)

This is probably the biggest undertaking I've had in a Rust project yet. I almost lost all this work just an hour ago to a bad rebase and blind force-push, but thankfully I was able to recover the correct HEAD from the reflog. I definitely learned my lesson there. Hopefully it wasn't all for naught.

Closes #2.

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
```
+1,231 additions
-1,568 deletions
```
Nice ;)

**Comment by cybergeek94** [comment]
Sorry, wanted to make sure it passed and I was out of the office this morning.

**Comment by LukasKalbertodt** [comment]
No problem, fortunately cargo can handle git refs :) And I always forget about time zones... 

When using this lib in the next time, I will think everything through a bit and may make some suggestions to improve API design or something. So you may hear from me (via issue or PR).

By the way: When you started working on the revival, the Iron community created a [plugin](https://github.com/iron/params) that can handle `multipart/form-data`. However, it's just working with Iron so this multipart lib is important IMO.

**Comment by cybergeek94** [comment]
Yeah, there's several competing solutions out there but I don't think any of them cover the client or test the client and server APIs against each other. Hopefully with some TLC this can become the go-to solution and we won't have too much duplication of effort.

**Comment by cybergeek94** [comment]
My primary concern in the client API is that the `Multipart::write_*()` methods take `self` by-value and return it, which makes it great for chaining all the way down to `.send()`, but could be pretty clunky in loops or nested scopes. I'm thinking those methods should take and return `&mut self` for chaining. Also, the thing about retaining errors until the end, I'm not sure if that's an anti-pattern or actually useful.

**Comment by LukasKalbertodt** [comment]
They could return `io::Result<&mut self>`. Chaining is then done via `and_then`. I guess thats the rusty way... But, as I said, I will think about that again.

**Comment by cybergeek94** [comment]
Yeah I just don't like how clunky that would be. I avoided that in the previous design by waiting to write all fields until `.send()` was called, but that required a `Vec` and trait objects and it was just a mess.

The only downside I can see to this design is losing the request object if an error is set when `.send()` is called. But you can also check for an error before you do that, and even remove it, so you only have to pay the ergonomics cost if you want to be more robust about handling errors.

**Comment by Manishearth** [comment]
FWIW Servo has some mime sniffing code (based on the spec) in its net crate that you can use for MIE detection.

**Comment by cybergeek94** [comment]
It'd be cool if that functionality was available in its own crate. I know there's one other MIME guessing crate out there but it basically does the same thing as `mime_guess`.

**Comment by Manishearth** [comment]
https://github.com/servo/servo/blob/master/components/net/mime_classifier.rs is basically independent and can be extracted into its own crate if you want.

**Pull request merged**
