### PR TITLE
mutlipart tries to read content disposition directly after boundary, …

### PR DESCRIPTION
**Pull request by nicolas-cherel**
There is a new line after the boundary and before the content-disposition part header.

I think that the real fix would be to add a \r\n behind the searched boundary string, but I could not make it work.

### CODE REVIEW

**Comment by cybergeek94** [comment]
Well, `.consume_boundary()` should probably eat the newline there.

**Comment by cybergeek94** [comment]
Either that, or the boundary needs to have the newline appended to it.

**Comment by nicolas-cherel** [comment]
Ok, did some further investigations, and we can't get away from this just with adding spaces or dashes with the actual searched boundary : 

 - we can't prefix it with \r\n because hyper gives use the body, those are already eaten, so we have to handle part end \r\n manually
 - we can't suffix it with \r\n because multipart end has a '--' suffix behind the boundary to mark last boundary to parse 

So we can't add the CRLF to the search boundary, and fiddling with consume_boundary() will require to make the boundary reader multipart aware. I think I'd be more practical to adjust the Multipart struct impl to make it aware of this, I'll try to make this work.

**Comment by cybergeek94** [comment]
Since `BoundaryReader` isn't a user type, I think it's okay for it to be aware of a few details. `.consume_boundary()` can just eat two extra bytes after the boundary, that's not hard.

**Comment by nicolas-cherel** [comment]
oops, did not see your comment, I might be missing some mail notification, anyway take a look a #11 and #12

**Comment by cybergeek94** [comment]
I've thought about it a bit, and I think I need to add a couple file/stream checks to the integration test. I think it's clear that just testing text fields isn't robust enough. I'm working on a branch now for it.

**Comment by nicolas-cherel** [comment]
ok, great, I was just looking for least-impact-yet-relevant fixes, so maybe we should close those PR. I'll work on my local branch with those fixes in the meantime.

I did not take time to write integration tests myself, but I was thinking about it too. Very happy to see this on track, I really needed it for the micro project I'm working on.

**Comment by cybergeek94** [comment]
Yeah, I've already got the new test working and it shows the gaping hole in the current test. It's clear that both sides need more work done.

**Comment by cybergeek94** [comment]
All right, I'm going to merge the `robust_tests` branch. You might need to merge/rebase some of your PRs.

**Comment by cybergeek94** [comment]
Closing in favor of #11.

**Pull request closed without merging**
